### ISSUE TITLE
g2mp & fpc 3.3.1 

### ISSUE THREAD

**Issue by codz01** [MrDan2345/g2mp#2]
Hi Dan
any attempt to make g2mp work with fpc 3.3.1 ?
last time i tested it it shows tons of errors

**Comment by MrDan2345** [comment]
hi, fpc 3.3.1 has not been officially released yet and I don't have to time now to build and test it from source. if I do get around to it, I will post an update here.

**Comment by codz01** [comment]
thank you very much :)
great engine & great design by the way

**Comment by MrDan2345** [comment]
it is not that great=) I am now working on a completely new iteration with multithreading, multi window system and vulkan renderer.

**Comment by codz01** [comment]
thats good news :) 
the thing that really impressed me is g2mp_toolkit program , you can easily design your game scene 
by the way , your new engine has only vulkan renderer backend ? i mean what about legacy opengl & d3d ?

**Comment by MrDan2345** [comment]
the toolkit will be a major part of the new engine as well. but legacy renderers will be discarded. which means no html5 builds also (g2mp will remain for that).

**Comment by codz01** [comment]
good , looking forward for the final result :) 
but isn't legacy renderers has wide range of users than vulkan ?

**Comment by MrDan2345** [comment]
sure they do, but they are also extremely limited. and since I am not making any money off my open source work the number of users does not matter.

**Comment by codz01** [comment]
fair enough ;)  
thanks for sharing your professional coding experience
